name: build_tests
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Run tox build tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: 3.8
          activate-environment: testenv
          channels: conda-forge
      - name: Setup conda python environments
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install -q -c conda-forge tox
          conda create -q -n py37 python=3.7
          conda create -q -n py39 python=3.9
      - name: Run pytest
        env:
          TOXENV: py37,py38,py39
        run: |
          export PY37_PATH=$CONDA/envs/py37/bin
          export PY39_PATH=$CONDA/envs/py39/bin
          export PATH=$PATH:$PY37_PATH:$PY39_PATH
          tox
      - name: Run code checks
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          TOXENV: typing,pypi-description,manifest,precom
        run: tox
